version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Vancouver'
      WEBPASSWORD: 'admin'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    env_file:
      - ./pihole-exporter.env
    ports:
      - 9617:9617