networks:
  pihole_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24

services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    networks:
      pihole_internal:
        ipv4_address: 10.0.1.2
    expose:
      - "5300/tcp"
      - "5300/udp"
    environment:
      TZ: ${TZ}
    volumes:
      - ../dns-setup/etc-dnscrypt-proxy:/config
    dns:
      - 1.1.1.1
    restart: unless-stopped
