services:
  keepalived:
    container_name: keepalived
    image: osixia/keepalived:2.0.20
    network_mode: service:pihole
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    privileged: true
    volumes:
      - ./keepalived.conf:/container/service/keepalived/assets/keepalived.conf:ro
      - ../dns-setup/check_pihole.sh:/usr/local/bin/check_pihole.sh:ro
      - ../dns-setup/notify.sh:/usr/local/bin/notify.sh:ro
    restart: unless-stopped
